// Course Curriculum Data for CSE and ICE
const CSE_CURRICULUM_DATA = {
  name: "B.Sc. in Computer Science & Engineering (CSE)",
  totalCredits: 148.5,
  categories: [
    { name: "Compulsory General Education", credits: 9 },
    { name: "Elective General Education", credits: 9 },
    { name: "Core Natural Science", credits: 11 },
    { name: "Core Mathematics & Statistics", credits: 12 },
    { name: "Core Computer Science & Engineering", credits: 73.5 },
    { name: "Core Capstone Project", credits: 6 },
    { name: "Major Area Requirements", credits: 20 },
    { name: "Non-Major Area Electives", credits: 8 }
  ],
  majors: [
    "Intelligent Systems & Data Science",
    "Software Engineering",
    "Communications & Networking",
    "Hardware Engineering"
  ],
  courses: [
  {
    "code": "ENG101",
    "title": "Basic English",
    "credits": "3",
    "prereq": "None",
    "category": "Compulsory General Education",
    "dept": "CSE",
    "year": 1,
    "semester": 1
  },
  {
    "code": "ENG102",
    "title": "Composition and Communication Skills",
    "credits": "3",
    "prereq": "ENG101",
    "category": "Compulsory General Education",
    "dept": "CSE",
    "year": 1,
    "semester": 2
  },
  {
    "code": "GEN226",
    "title": "Emergence of Bangladesh",
    "credits": "3",
    "prereq": "ENG102",
    "category": "Compulsory General Education",
    "dept": "CSE",
    "year": 2,
    "semester": 1
  },
  {
    "code": "PHY109",
    "title": "Engineering Physics-I (Introductory Classical Physics)",
    "credits": "3+1=4",
    "prereq": "MAT102",
    "category": "Core Natural Science",
    "dept": "CSE",
    "year": 1,
    "semester": 3
  },
  {
    "code": "PHY209",
    "title": "Engineering Physics-II (Introductory Quantum Physics)",
    "credits": "3+0=3",
    "prereq": "MAT205",
    "category": "Core Natural Science",
    "dept": "CSE",
    "year": 2,
    "semester": 3
  },
  {
    "code": "CHE109",
    "title": "Engineering Chemistry",
    "credits": "3+1=4",
    "prereq": "None",
    "category": "Core Natural Science",
    "dept": "CSE",
    "year": 1,
    "semester": 2
  },
  {
    "code": "MAT101",
    "title": "Differential and Integral Calculus",
    "credits": "3",
    "prereq": "None",
    "category": "Core Mathematics & Statistics",
    "dept": "CSE",
    "year": 1,
    "semester": 1
  },
  {
    "code": "MAT102",
    "title": "Differential Equations and Special Functions",
    "credits": "3",
    "prereq": "MAT101",
    "category": "Core Mathematics & Statistics",
    "dept": "CSE",
    "year": 1,
    "semester": 2
  },
  {
    "code": "MAT104",
    "title": "Coordinate Geometry and Vector Analysis",
    "credits": "3",
    "prereq": "MAT101",
    "category": "Core Mathematics & Statistics",
    "dept": "CSE",
    "year": 1,
    "semester": 3
  },
  {
    "code": "MAT205",
    "title": "Linear Algebra and Complex Variable",
    "credits": "3",
    "prereq": "MAT102",
    "category": "Core Mathematics & Statistics",
    "dept": "CSE",
    "year": 2,
    "semester": 2
  },
  {
    "code": "STA102",
    "title": "Statistics and Probability",
    "credits": "3",
    "prereq": "None",
    "category": "Core Mathematics & Statistics",
    "dept": "CSE",
    "year": 2,
    "semester": 1
  },
  {
    "code": "CSE103",
    "title": "Structured Programming",
    "credits": "3+1.5=4.5",
    "prereq": "None",
    "category": "Core Computer Science & Engineering",
    "dept": "CSE",
    "year": 1,
    "semester": 1
  },
  {
    "code": "CSE106",
    "title": "Discrete Mathematics",
    "credits": "3+0=3",
    "prereq": "CSE103",
    "category": "Core Computer Science & Engineering",
    "dept": "CSE",
    "year": 1,
    "semester": 2
  },
  {
    "code": "CSE110",
    "title": "Object Oriented Programming",
    "credits": "3+1.5=4.5",
    "prereq": "CSE106",
    "category": "Core Computer Science & Engineering",
    "dept": "CSE",
    "year": 1,
    "semester": 3
  },
  {
    "code": "CSE200",
    "title": "Computer-Aided Engineering Drawing",
    "credits": "0+1=1",
    "prereq": "None",
    "category": "Core Computer Science & Engineering",
    "dept": "CSE",
    "year": 2,
    "semester": 1
  },
  {
    "code": "CSE209",
    "title": "Electrical Circuits",
    "credits": "3+1=4",
    "prereq": "None",
    "category": "Core Computer Science & Engineering",
    "dept": "CSE",
    "year": 2,
    "semester": 1
  },
  {
    "code": "CSE207",
    "title": "Data Structures",
    "credits": "3+1=4",
    "prereq": "CSE110",
    "category": "Core Computer Science & Engineering",
    "dept": "CSE",
    "year": 2,
    "semester": 2
  },
  {
    "code": "CSE251",
    "title": "Electronic Circuits",
    "credits": "3+1=4",
    "prereq": "CSE209",
    "category": "Core Computer Science & Engineering",
    "dept": "CSE",
    "year": 2,
    "semester": 2
  },
  {
    "code": "CSE325",
    "title": "Operating Systems",
    "credits": "3+1=4",
    "prereq": "CSE207",
    "category": "Core Computer Science & Engineering",
    "dept": "CSE",
    "year": 2,
    "semester": 3
  },
  {
    "code": "CSE246",
    "title": "Algorithms",
    "credits": "3+1.5=4.5",
    "prereq": "CSE207",
    "category": "Core Computer Science & Engineering",
    "dept": "CSE",
    "year": 3,
    "semester": 1
  },
  {
    "code": "CSE302",
    "title": "Database Systems",
    "credits": "3+1.5=4.5",
    "prereq": "CSE106",
    "category": "Core Computer Science & Engineering",
    "dept": "CSE",
    "year": 3,
    "semester": 1
  },
  {
    "code": "CSE345",
    "title": "Digital Logic Design",
    "credits": "3+1=4",
    "prereq": "CSE251",
    "category": "Core Computer Science & Engineering",
    "dept": "CSE",
    "year": 3,
    "semester": 2
  },
  {
    "code": "CSE347",
    "title": "Information System Analysis and Design",
    "credits": "3+1=4",
    "prereq": "CSE302",
    "category": "Core Computer Science & Engineering",
    "dept": "CSE",
    "year": 3,
    "semester": 2
  },
  {
    "code": "CSE360",
    "title": "Computer Architecture",
    "credits": "3+0=3",
    "prereq": "CSE221",
    "category": "Core Computer Science & Engineering",
    "dept": "CSE",
    "year": 3,
    "semester": 3
  },
  {
    "code": "CSE405",
    "title": "Computer Networks",
    "credits": "3+1=4",
    "prereq": "CSE326",
    "category": "Core Computer Science & Engineering",
    "dept": "CSE",
    "year": 3,
    "semester": 3
  },
  {
    "code": "CSE407",
    "title": "Green Computing",
    "credits": "3+0=3",
    "prereq": "CSE405",
    "category": "Core Computer Science & Engineering",
    "dept": "CSE",
    "year": 4,
    "semester": 1
  },
  {
    "code": "CSE487",
    "title": "Cyber Security, Ethics and Law",
    "credits": "3+0=3",
    "prereq": "CSE405",
    "category": "Core Computer Science & Engineering",
    "dept": "CSE",
    "year": 4,
    "semester": 2
  },
  {
    "code": "CSE495",
    "title": "IT Project Management and Entrepreneurship",
    "credits": "3+0=3",
    "prereq": "CSE347",
    "category": "Major: ",
    "majorTrack": "",
    "trackType": "",
    "dept": "CSE",
    "year": 4,
    "semester": 1
  },
  {
    "code": "CSE400",
    "title": "Capstone Project",
    "credits": "0+6=6",
    "prereq": "Completed at least 105 credit hours",
    "category": "Major: ",
    "majorTrack": "",
    "trackType": "",
    "dept": "CSE",
    "year": 4,
    "semester": 1
  },
  {
    "code": "CSE303",
    "title": "Statistics for Data Science",
    "credits": "3+1=4",
    "prereq": "STA102",
    "category": "Major: Intelligent Systems & Data Science",
    "majorTrack": "Intelligent Systems & Data Science",
    "trackType": "Compulsory Major",
    "dept": "CSE",
    "year": 4,
    "semester": 1
  },
  {
    "code": "CSE366",
    "title": "Artificial Intelligence",
    "credits": "3+1=4",
    "prereq": "CSE326",
    "category": "Major: Intelligent Systems & Data Science",
    "majorTrack": "Intelligent Systems & Data Science",
    "trackType": "Compulsory Major",
    "dept": "CSE",
    "year": 4,
    "semester": 1
  },
  {
    "code": "CSE420",
    "title": "Computer Graphics",
    "credits": "3+1=4",
    "prereq": "CSE326",
    "category": "Major: Intelligent Systems & Data Science",
    "majorTrack": "Intelligent Systems & Data Science",
    "trackType": "Elective Major",
    "dept": "CSE",
    "year": 4,
    "semester": 1
  },
  {
    "code": "CSE438",
    "title": "Digital Image Processing",
    "credits": "3+1=4",
    "prereq": "CSE326",
    "category": "Major: Intelligent Systems & Data Science",
    "majorTrack": "Intelligent Systems & Data Science",
    "trackType": "Elective Major",
    "dept": "CSE",
    "year": 4,
    "semester": 1
  },
  {
    "code": "CSE445",
    "title": "Computer Vision",
    "credits": "3+1=4",
    "prereq": "CSE326",
    "category": "Major: Intelligent Systems & Data Science",
    "majorTrack": "Intelligent Systems & Data Science",
    "trackType": "Elective Major",
    "dept": "CSE",
    "year": 4,
    "semester": 1
  },
  {
    "code": "CSE452",
    "title": "Distributed Systems and Algorithms",
    "credits": "3+1=4",
    "prereq": "CSE221",
    "category": "Major: Intelligent Systems & Data Science",
    "majorTrack": "Intelligent Systems & Data Science",
    "trackType": "Elective Major",
    "dept": "CSE",
    "year": 4,
    "semester": 1
  },
  {
    "code": "CSE474",
    "title": "Pattern Recognition",
    "credits": "3+1=4",
    "prereq": "CSE366",
    "category": "Major: Intelligent Systems & Data Science",
    "majorTrack": "Intelligent Systems & Data Science",
    "trackType": "Elective Major",
    "dept": "CSE",
    "year": 4,
    "semester": 1
  },
  {
    "code": "CSE475",
    "title": "Machine Learning",
    "credits": "3+1=4",
    "prereq": "CSE366",
    "category": "Major: Intelligent Systems & Data Science",
    "majorTrack": "Intelligent Systems & Data Science",
    "trackType": "Elective Major",
    "dept": "CSE",
    "year": 4,
    "semester": 1
  },
  {
    "code": "CSE477",
    "title": "Data Mining",
    "credits": "3+1=4",
    "prereq": "CSE366",
    "category": "Major: Intelligent Systems & Data Science",
    "majorTrack": "Intelligent Systems & Data Science",
    "trackType": "Elective Major",
    "dept": "CSE",
    "year": 4,
    "semester": 1
  },
  {
    "code": "CSE481",
    "title": "Nature-Inspired Computing",
    "credits": "3+1=4",
    "prereq": "CSE326",
    "category": "Major: Intelligent Systems & Data Science",
    "majorTrack": "Intelligent Systems & Data Science",
    "trackType": "Elective Major",
    "dept": "CSE",
    "year": 4,
    "semester": 1
  },
  {
    "code": "CSE486",
    "title": "Bioinformatics Algorithms",
    "credits": "3+1=4",
    "prereq": "CSE326",
    "category": "Major: Intelligent Systems & Data Science",
    "majorTrack": "Intelligent Systems & Data Science",
    "trackType": "Elective Major",
    "dept": "CSE",
    "year": 4,
    "semester": 1
  },
  {
    "code": "CSE488",
    "title": "Big Data Analytics",
    "credits": "3+1=4",
    "prereq": "CSE302",
    "category": "Major: Intelligent Systems & Data Science",
    "majorTrack": "Intelligent Systems & Data Science",
    "trackType": "Elective Major",
    "dept": "CSE",
    "year": 4,
    "semester": 1
  },
  {
    "code": "CSE412",
    "title": "Software Engineering",
    "credits": "3+1=4",
    "prereq": "CSE347",
    "category": "Major: Software Engineering",
    "majorTrack": "Software Engineering",
    "trackType": "Compulsory Major",
    "dept": "CSE",
    "year": 4,
    "semester": 1
  },
  {
    "code": "CSE430",
    "title": "Software Testing and Quality Assurance",
    "credits": "3+1=4",
    "prereq": "CSE412",
    "category": "Major: Software Engineering",
    "majorTrack": "Software Engineering",
    "trackType": "Compulsory Major",
    "dept": "CSE",
    "year": 4,
    "semester": 1
  },
  {
    "code": "CSE422",
    "title": "Simulation and Modeling",
    "credits": "3+1=4",
    "prereq": "CSE326",
    "category": "Major: Software Engineering",
    "majorTrack": "Software Engineering",
    "trackType": "Elective Major",
    "dept": "CSE",
    "year": 4,
    "semester": 1
  },
  {
    "code": "CSE423",
    "title": "Software Architecture",
    "credits": "3+1=4",
    "prereq": "CSE412",
    "category": "Major: Software Engineering",
    "majorTrack": "Software Engineering",
    "trackType": "Elective Major",
    "dept": "CSE",
    "year": 4,
    "semester": 1
  },
  {
    "code": "CSE428",
    "title": "Human Computer Interactions",
    "credits": "3+1=4",
    "prereq": "CSE412",
    "category": "Major: Software Engineering",
    "majorTrack": "Software Engineering",
    "trackType": "Elective Major",
    "dept": "CSE",
    "year": 4,
    "semester": 1
  },
  {
    "code": "CSE464",
    "title": "Advanced Database System",
    "credits": "3+1=4",
    "prereq": "CSE302",
    "category": "Major: Software Engineering",
    "majorTrack": "Software Engineering",
    "trackType": "Elective Major",
    "dept": "CSE",
    "year": 4,
    "semester": 1
  },
  {
    "code": "CSE479",
    "title": "Web Programming",
    "credits": "3+1=4",
    "prereq": "CSE302",
    "category": "Major: Software Engineering",
    "majorTrack": "Software Engineering",
    "trackType": "Elective Major",
    "dept": "CSE",
    "year": 4,
    "semester": 1
  },
  {
    "code": "CSE489",
    "title": "Mobile Programming",
    "credits": "3+1=4",
    "prereq": "CSE326",
    "category": "Major: Software Engineering",
    "majorTrack": "Software Engineering",
    "trackType": "Elective Major",
    "dept": "CSE",
    "year": 4,
    "semester": 1
  },
  {
    "code": "CSE350",
    "title": "Data Communications",
    "credits": "3+1=4",
    "prereq": "CSE251",
    "category": "Major: Communications & Networking",
    "majorTrack": "Communications & Networking",
    "trackType": "Compulsory Major",
    "dept": "CSE",
    "year": 4,
    "semester": 1
  },
  {
    "code": "CSE432",
    "title": "Digital Signal Processing",
    "credits": "3+1=4",
    "prereq": "CSE326",
    "category": "Major: Communications & Networking",
    "majorTrack": "Communications & Networking",
    "trackType": "Compulsory Major",
    "dept": "CSE",
    "year": 4,
    "semester": 1
  },
  {
    "code": "CSE453",
    "title": "Wireless Networks",
    "credits": "3+1=4",
    "prereq": "CSE405",
    "category": "Major: Communications & Networking",
    "majorTrack": "Communications & Networking",
    "trackType": "Elective Major",
    "dept": "CSE",
    "year": 4,
    "semester": 1
  },
  {
    "code": "CSE457",
    "title": "Cellular Networks",
    "credits": "3+1=4",
    "prereq": "CSE405",
    "category": "Major: Communications & Networking",
    "majorTrack": "Communications & Networking",
    "trackType": "Elective Major",
    "dept": "CSE",
    "year": 4,
    "semester": 1
  },
  {
    "code": "CSE472",
    "title": "Advanced Network Services and Management",
    "credits": "3+1=4",
    "prereq": "CSE405",
    "category": "Major: Communications & Networking",
    "majorTrack": "Communications & Networking",
    "trackType": "Elective Major",
    "dept": "CSE",
    "year": 4,
    "semester": 1
  },
  {
    "code": "CSE473",
    "title": "Network Security and Systems",
    "credits": "3+1=4",
    "prereq": "CSE405",
    "category": "Major: Communications & Networking",
    "majorTrack": "Communications & Networking",
    "trackType": "Elective Major",
    "dept": "CSE",
    "year": 4,
    "semester": 1
  },
  {
    "code": "CSE355",
    "title": "Digital System Design",
    "credits": "3+1=4",
    "prereq": "CSE345",
    "category": "Major: Hardware Engineering",
    "majorTrack": "Hardware Engineering",
    "trackType": "Compulsory Major",
    "dept": "CSE",
    "year": 4,
    "semester": 1
  },
  {
    "code": "CSE442",
    "title": "Microprocessors and Microcontrollers",
    "credits": "3+1=4",
    "prereq": "CSE360",
    "category": "Major: Hardware Engineering",
    "majorTrack": "Hardware Engineering",
    "trackType": "Compulsory Major",
    "dept": "CSE",
    "year": 4,
    "semester": 1
  },
  {
    "code": "CSE406",
    "title": "Internet of Things",
    "credits": "3+1=4",
    "prereq": "CSE405",
    "category": "Major: Hardware Engineering",
    "majorTrack": "Hardware Engineering",
    "trackType": "Elective Major",
    "dept": "CSE",
    "year": 4,
    "semester": 1
  },
  {
    "code": "CSE446",
    "title": "ASIC Design Using FPGA",
    "credits": "3+1=4",
    "prereq": "CSE345",
    "category": "Major: Hardware Engineering",
    "majorTrack": "Hardware Engineering",
    "trackType": "Elective Major",
    "dept": "CSE",
    "year": 4,
    "semester": 1
  },
  {
    "code": "CSE491",
    "title": "VLSI Design",
    "credits": "3+1=4",
    "prereq": "CSE345",
    "category": "Major: Hardware Engineering",
    "majorTrack": "Hardware Engineering",
    "trackType": "Elective Major",
    "dept": "CSE",
    "year": 4,
    "semester": 1
  },
  {
    "code": "CSE492",
    "title": "Robotics",
    "credits": "3+1=4",
    "prereq": "CSE366",
    "category": "Major: Hardware Engineering",
    "majorTrack": "Hardware Engineering",
    "trackType": "Elective Major",
    "dept": "CSE",
    "year": 4,
    "semester": 1
  },
  {
    "code": "CSE494",
    "title": "Embedded Systems",
    "credits": "3+1=4",
    "prereq": "CSE442",
    "category": "Major: Hardware Engineering",
    "majorTrack": "Hardware Engineering",
    "trackType": "Elective Major",
    "dept": "CSE",
    "year": 4,
    "semester": 1
  },
  {
    "code": "CSE225",
    "title": "Numerical Methods",
    "credits": "3+1=4",
    "prereq": "CSE103",
    "category": "Non-Major: Computational Theory",
    "majorTrack": "Computational Theory",
    "trackType": "Elective",
    "dept": "CSE",
    "year": 4,
    "semester": 1
  },
  {
    "code": "CSE313",
    "title": "Theory of Computations",
    "credits": "3+0=3",
    "prereq": "CSE326",
    "category": "Non-Major: Computational Theory",
    "majorTrack": "Computational Theory",
    "trackType": "Elective",
    "dept": "CSE",
    "year": 4,
    "semester": 1
  },
  {
    "code": "CSE460",
    "title": "Cryptography",
    "credits": "3+0=3",
    "prereq": "CSE326",
    "category": "Non-Major: Computational Theory",
    "majorTrack": "Computational Theory",
    "trackType": "Elective",
    "dept": "CSE",
    "year": 4,
    "semester": 1
  },
  {
    "code": "CSE471",
    "title": "Compiler Design",
    "credits": "3+1=4",
    "prereq": "CSE326",
    "category": "Non-Major: Computational Theory",
    "majorTrack": "Computational Theory",
    "trackType": "Elective",
    "dept": "CSE",
    "year": 4,
    "semester": 1
  },
  {
    "code": "CSE483",
    "title": "Graph Theory",
    "credits": "3+0=3",
    "prereq": "CSE326",
    "category": "Non-Major: Computational Theory",
    "majorTrack": "Computational Theory",
    "trackType": "Elective",
    "dept": "CSE",
    "year": 4,
    "semester": 1
  },
  {
    "code": "CSE484",
    "title": "Computational Geometry",
    "credits": "3+0=3",
    "prereq": "CSE326",
    "category": "Non-Major: Computational Theory",
    "majorTrack": "Computational Theory",
    "trackType": "Elective",
    "dept": "CSE",
    "year": 4,
    "semester": 1
  }
]
};

const ICE_CURRICULUM_DATA = {
  name: "B.Sc. in Information & Communication Engineering (ICE)",
  totalCredits: 140,
  categories: [
    { name: "A. General Education Requirements", credits: 21 },
    { name: "B. Mathematics & Basic Sciences", credits: 26 },
    { name: "C. ICE Core", credits: 81 },
    { name: "D. Technical Electives", credits: 12 }
  ],
  groups: [
    "Compulsory General Education",
    "Optional General Education",
    "Optional Business & Economics",
    "Mathematics & Basic Sciences",
    "ICE Core",
    "Group A (Information Technology)",
    "Group B (Communication)"
  ],
  courses: [
  {
    "code": "ENG101",
    "title": "Basic English",
    "credits": "3",
    "prereq": "None",
    "category": "A. General Education Requirements",
    "dept": "ICE",
    "group": "(i) Compulsory General Education",
    "year": 1,
    "semester": 1
  },
  {
    "code": "ENG102",
    "title": "Composition & Communication Skills",
    "credits": "3",
    "prereq": "None",
    "category": "A. General Education Requirements",
    "dept": "ICE",
    "group": "(i) Compulsory General Education",
    "year": 1,
    "semester": 1
  },
  {
    "code": "GEN226",
    "title": "Emergence of Bangladesh",
    "credits": "3",
    "prereq": "None",
    "category": "A. General Education Requirements",
    "dept": "ICE",
    "group": "(i) Compulsory General Education",
    "year": 2,
    "semester": 1
  },
  {
    "code": "GEN201",
    "title": "Bangladesh Studies",
    "credits": "3",
    "prereq": "None",
    "category": "A. General Education Requirements",
    "dept": "ICE",
    "group": "(ii) Optional General Education",
    "year": 2,
    "semester": 1
  },
  {
    "code": "GEN202",
    "title": "Eastern Culture & Heritage",
    "credits": "3",
    "prereq": "None",
    "category": "A. General Education Requirements",
    "dept": "ICE",
    "group": "(ii) Optional General Education",
    "year": 2,
    "semester": 1
  },
  {
    "code": "GEN203",
    "title": "Ecological System and Environment",
    "credits": "3",
    "prereq": "None",
    "category": "A. General Education Requirements",
    "dept": "ICE",
    "group": "(ii) Optional General Education",
    "year": 2,
    "semester": 1
  },
  {
    "code": "GEN204",
    "title": "Western Thought",
    "credits": "3",
    "prereq": "None",
    "category": "A. General Education Requirements",
    "dept": "ICE",
    "group": "(ii) Optional General Education",
    "year": 2,
    "semester": 1
  },
  {
    "code": "GEN205",
    "title": "Introduction to Psychology",
    "credits": "3",
    "prereq": "None",
    "category": "A. General Education Requirements",
    "dept": "ICE",
    "group": "(ii) Optional General Education",
    "year": 2,
    "semester": 1
  },
  {
    "code": "GEN207",
    "title": "Industrial Psychology",
    "credits": "3",
    "prereq": "None",
    "category": "A. General Education Requirements",
    "dept": "ICE",
    "group": "(ii) Optional General Education",
    "year": 2,
    "semester": 1
  },
  {
    "code": "GEN208",
    "title": "Introduction to Philosophy",
    "credits": "3",
    "prereq": "None",
    "category": "A. General Education Requirements",
    "dept": "ICE",
    "group": "(ii) Optional General Education",
    "year": 2,
    "semester": 1
  },
  {
    "code": "GEN209",
    "title": "Introduction to Social Psychology",
    "credits": "3",
    "prereq": "None",
    "category": "A. General Education Requirements",
    "dept": "ICE",
    "group": "(ii) Optional General Education",
    "year": 2,
    "semester": 1
  },
  {
    "code": "GEN210",
    "title": "International Relations",
    "credits": "3",
    "prereq": "None",
    "category": "A. General Education Requirements",
    "dept": "ICE",
    "group": "(ii) Optional General Education",
    "year": 2,
    "semester": 1
  },
  {
    "code": "GEN211",
    "title": "Concepts of Journalism & Media Studies",
    "credits": "3",
    "prereq": "None",
    "category": "A. General Education Requirements",
    "dept": "ICE",
    "group": "(ii) Optional General Education",
    "year": 2,
    "semester": 1
  },
  {
    "code": "GEN212",
    "title": "Women in Development",
    "credits": "3",
    "prereq": "None",
    "category": "A. General Education Requirements",
    "dept": "ICE",
    "group": "(ii) Optional General Education",
    "year": 2,
    "semester": 1
  },
  {
    "code": "GEN213",
    "title": "Introduction to German Language",
    "credits": "3",
    "prereq": "None",
    "category": "A. General Education Requirements",
    "dept": "ICE",
    "group": "(ii) Optional General Education",
    "year": 2,
    "semester": 1
  },
  {
    "code": "GEN214",
    "title": "Introduction to Development Studies",
    "credits": "3",
    "prereq": "None",
    "category": "A. General Education Requirements",
    "dept": "ICE",
    "group": "(ii) Optional General Education",
    "year": 2,
    "semester": 1
  },
  {
    "code": "GEN215",
    "title": "Introduction to French Language",
    "credits": "3",
    "prereq": "None",
    "category": "A. General Education Requirements",
    "dept": "ICE",
    "group": "(ii) Optional General Education",
    "year": 2,
    "semester": 1
  },
  {
    "code": "GEN216",
    "title": "Introduction to Spanish Language",
    "credits": "3",
    "prereq": "None",
    "category": "A. General Education Requirements",
    "dept": "ICE",
    "group": "(ii) Optional General Education",
    "year": 2,
    "semester": 1
  },
  {
    "code": "GEN217",
    "title": "Introduction to Chinese Language",
    "credits": "3",
    "prereq": "None",
    "category": "A. General Education Requirements",
    "dept": "ICE",
    "group": "(ii) Optional General Education",
    "year": 2,
    "semester": 1
  },
  {
    "code": "GEN218",
    "title": "Introduction to Arabic Language",
    "credits": "3",
    "prereq": "None",
    "category": "A. General Education Requirements",
    "dept": "ICE",
    "group": "(ii) Optional General Education",
    "year": 2,
    "semester": 1
  },
  {
    "code": "GEN220",
    "title": "Principles of Public Relations",
    "credits": "3",
    "prereq": "None",
    "category": "A. General Education Requirements",
    "dept": "ICE",
    "group": "(ii) Optional General Education",
    "year": 2,
    "semester": 1
  },
  {
    "code": "GEN221",
    "title": "Globalization, Development and Change",
    "credits": "3",
    "prereq": "None",
    "category": "A. General Education Requirements",
    "dept": "ICE",
    "group": "(ii) Optional General Education",
    "year": 2,
    "semester": 1
  },
  {
    "code": "GEN223",
    "title": "Contemporary Security Studies in Asia-Pacific",
    "credits": "3",
    "prereq": "None",
    "category": "A. General Education Requirements",
    "dept": "ICE",
    "group": "(ii) Optional General Education",
    "year": 2,
    "semester": 1
  },
  {
    "code": "GEN224",
    "title": "Bangla Language",
    "credits": "3",
    "prereq": "None",
    "category": "A. General Education Requirements",
    "dept": "ICE",
    "group": "(ii) Optional General Education",
    "year": 2,
    "semester": 1
  },
  {
    "code": "GEN239",
    "title": "Professional Ethics",
    "credits": "3",
    "prereq": "None",
    "category": "A. General Education Requirements",
    "dept": "ICE",
    "group": "(ii) Optional General Education",
    "year": 2,
    "semester": 1
  },
  {
    "code": "POP201",
    "title": "Health Challenges of Adolescents and Youth",
    "credits": "3",
    "prereq": "None",
    "category": "A. General Education Requirements",
    "dept": "ICE",
    "group": "(ii) Optional General Education",
    "year": 2,
    "semester": 1
  },
  {
    "code": "POP202",
    "title": "Introduction to Public Health",
    "credits": "3",
    "prereq": "None",
    "category": "A. General Education Requirements",
    "dept": "ICE",
    "group": "(ii) Optional General Education",
    "year": 2,
    "semester": 1
  },
  {
    "code": "POP203",
    "title": "Introduction to Population Studies",
    "credits": "3",
    "prereq": "None",
    "category": "A. General Education Requirements",
    "dept": "ICE",
    "group": "(ii) Optional General Education",
    "year": 2,
    "semester": 1
  },
  {
    "code": "SOC101",
    "title": "Introduction to Sociology",
    "credits": "3",
    "prereq": "None",
    "category": "A. General Education Requirements",
    "dept": "ICE",
    "group": "(ii) Optional General Education",
    "year": 1,
    "semester": 1
  },
  {
    "code": "SOC102",
    "title": "Introduction to Anthropology",
    "credits": "3",
    "prereq": "None",
    "category": "A. General Education Requirements",
    "dept": "ICE",
    "group": "(ii) Optional General Education",
    "year": 1,
    "semester": 1
  },
  {
    "code": "ACT101",
    "title": "Financial Accounting",
    "credits": "3",
    "prereq": "None",
    "category": "A. General Education Requirements",
    "dept": "ICE",
    "group": "(iii) Optional Business & Economics",
    "year": 1,
    "semester": 1
  },
  {
    "code": "BUS101",
    "title": "Introduction to Business",
    "credits": "3",
    "prereq": "None",
    "category": "A. General Education Requirements",
    "dept": "ICE",
    "group": "(iii) Optional Business & Economics",
    "year": 1,
    "semester": 1
  },
  {
    "code": "BUS321",
    "title": "Business for Engineering and Technology",
    "credits": "3",
    "prereq": "None",
    "category": "A. General Education Requirements",
    "dept": "ICE",
    "group": "(iii) Optional Business & Economics",
    "year": 3,
    "semester": 1
  },
  {
    "code": "ECO101",
    "title": "Principles of Microeconomics",
    "credits": "3",
    "prereq": "None",
    "category": "A. General Education Requirements",
    "dept": "ICE",
    "group": "(iii) Optional Business & Economics",
    "year": 1,
    "semester": 1
  },
  {
    "code": "ECO102",
    "title": "Introduction to Macroeconomics",
    "credits": "3",
    "prereq": "None",
    "category": "A. General Education Requirements",
    "dept": "ICE",
    "group": "(iii) Optional Business & Economics",
    "year": 1,
    "semester": 1
  },
  {
    "code": "FIN101",
    "title": "Principles of Finance",
    "credits": "3",
    "prereq": "None",
    "category": "A. General Education Requirements",
    "dept": "ICE",
    "group": "(iii) Optional Business & Economics",
    "year": 1,
    "semester": 1
  },
  {
    "code": "MGT101",
    "title": "Principles of Management",
    "credits": "3",
    "prereq": "None",
    "category": "A. General Education Requirements",
    "dept": "ICE",
    "group": "(iii) Optional Business & Economics",
    "year": 1,
    "semester": 1
  },
  {
    "code": "MIS101",
    "title": "Introduction to Management",
    "credits": "3",
    "prereq": "None",
    "category": "A. General Education Requirements",
    "dept": "ICE",
    "group": "(iii) Optional Business & Economics",
    "year": 1,
    "semester": 1
  },
  {
    "code": "MKT101",
    "title": "Principles of Marketing",
    "credits": "3",
    "prereq": "None",
    "category": "A. General Education Requirements",
    "dept": "ICE",
    "group": "(iii) Optional Business & Economics",
    "year": 1,
    "semester": 1
  },
  {
    "code": "MAT101",
    "title": "Differential and Integral Calculus",
    "credits": "3",
    "prereq": "None",
    "category": "B. Mathematics & Basic Sciences",
    "dept": "ICE",
    "group": "Mathematics & Basic Sciences",
    "year": 1,
    "semester": 1
  },
  {
    "code": "MAT102",
    "title": "Differential Equations & Special Functions",
    "credits": "3",
    "prereq": "None",
    "category": "B. Mathematics & Basic Sciences",
    "dept": "ICE",
    "group": "Mathematics & Basic Sciences",
    "year": 1,
    "semester": 1
  },
  {
    "code": "MAT104",
    "title": "Coordinate Geometry and Vector Analysis",
    "credits": "3",
    "prereq": "None",
    "category": "B. Mathematics & Basic Sciences",
    "dept": "ICE",
    "group": "Mathematics & Basic Sciences",
    "year": 1,
    "semester": 1
  },
  {
    "code": "MAT205",
    "title": "Linear Algebra & Complex Variables",
    "credits": "3",
    "prereq": "None",
    "category": "B. Mathematics & Basic Sciences",
    "dept": "ICE",
    "group": "Mathematics & Basic Sciences",
    "year": 2,
    "semester": 1
  },
  {
    "code": "PHY109",
    "title": "Engineering Physics -I",
    "credits": "3",
    "prereq": "None",
    "category": "B. Mathematics & Basic Sciences",
    "dept": "ICE",
    "group": "Mathematics & Basic Sciences",
    "year": 1,
    "semester": 1
  },
  {
    "code": "PHY209",
    "title": "Engineering Physics -II",
    "credits": "3",
    "prereq": "None",
    "category": "B. Mathematics & Basic Sciences",
    "dept": "ICE",
    "group": "Mathematics & Basic Sciences",
    "year": 2,
    "semester": 1
  },
  {
    "code": "CHE109",
    "title": "Engineering Chemistry -I",
    "credits": "3",
    "prereq": "None",
    "category": "B. Mathematics & Basic Sciences",
    "dept": "ICE",
    "group": "Mathematics & Basic Sciences",
    "year": 1,
    "semester": 1
  },
  {
    "code": "STA102",
    "title": "Probability and Statistics",
    "credits": "3",
    "prereq": "None",
    "category": "B. Mathematics & Basic Sciences",
    "dept": "ICE",
    "group": "Mathematics & Basic Sciences",
    "year": 1,
    "semester": 1
  },
  {
    "code": "ICE103",
    "title": "Structured Programming",
    "credits": "4 (3+1)",
    "prereq": "None",
    "category": "C. ICE Core",
    "dept": "ICE",
    "group": "ICE Core",
    "year": 1,
    "semester": 1
  },
  {
    "code": "ICE107",
    "title": "Object Oriented Programming",
    "credits": "4 (3+1)",
    "prereq": "None",
    "category": "C. ICE Core",
    "dept": "ICE",
    "group": "ICE Core",
    "year": 1,
    "semester": 1
  },
  {
    "code": "ICE109",
    "title": "Electrical Circuits",
    "credits": "4 (3+1)",
    "prereq": "None",
    "category": "C. ICE Core",
    "dept": "ICE",
    "group": "ICE Core",
    "year": 1,
    "semester": 1
  },
  {
    "code": "ICE204",
    "title": "Discrete Mathematics",
    "credits": "3",
    "prereq": "None",
    "category": "C. ICE Core",
    "dept": "ICE",
    "group": "ICE Core",
    "year": 2,
    "semester": 1
  },
  {
    "code": "ICE207",
    "title": "Data Structures",
    "credits": "4 (3+1)",
    "prereq": "None",
    "category": "C. ICE Core",
    "dept": "ICE",
    "group": "ICE Core",
    "year": 2,
    "semester": 1
  },
  {
    "code": "ICE213",
    "title": "Electronic Circuits",
    "credits": "4 (3+1)",
    "prereq": "None",
    "category": "C. ICE Core",
    "dept": "ICE",
    "group": "ICE Core",
    "year": 2,
    "semester": 1
  },
  {
    "code": "ICE216",
    "title": "Signals & Systems",
    "credits": "3",
    "prereq": "None",
    "category": "C. ICE Core",
    "dept": "ICE",
    "group": "ICE Core",
    "year": 2,
    "semester": 1
  },
  {
    "code": "ICE217",
    "title": "Digital Electronics",
    "credits": "4 (3+1)",
    "prereq": "None",
    "category": "C. ICE Core",
    "dept": "ICE",
    "group": "ICE Core",
    "year": 2,
    "semester": 1
  },
  {
    "code": "ICE245",
    "title": "Algorithms",
    "credits": "4 (3+1)",
    "prereq": "None",
    "category": "C. ICE Core",
    "dept": "ICE",
    "group": "ICE Core",
    "year": 2,
    "semester": 1
  },
  {
    "code": "ICE275",
    "title": "Operating Systems",
    "credits": "3",
    "prereq": "None",
    "category": "C. ICE Core",
    "dept": "ICE",
    "group": "ICE Core",
    "year": 2,
    "semester": 1
  },
  {
    "code": "ICE302",
    "title": "Computer Communications & Networks",
    "credits": "4 (3+1)",
    "prereq": "None",
    "category": "C. ICE Core",
    "dept": "ICE",
    "group": "ICE Core",
    "year": 3,
    "semester": 1
  },
  {
    "code": "ICE305",
    "title": "Database Systems",
    "credits": "4 (3+1)",
    "prereq": "None",
    "category": "C. ICE Core",
    "dept": "ICE",
    "group": "ICE Core",
    "year": 3,
    "semester": 1
  },
  {
    "code": "ICE310",
    "title": "Electromagnetic Theory",
    "credits": "3",
    "prereq": "None",
    "category": "C. ICE Core",
    "dept": "ICE",
    "group": "ICE Core",
    "year": 3,
    "semester": 1
  },
  {
    "code": "ICE312",
    "title": "Communication Theory",
    "credits": "3",
    "prereq": "None",
    "category": "C. ICE Core",
    "dept": "ICE",
    "group": "ICE Core",
    "year": 3,
    "semester": 1
  },
  {
    "code": "ICE313",
    "title": "Microprocessors & Interfacing",
    "credits": "4 (3+1)",
    "prereq": "None",
    "category": "C. ICE Core",
    "dept": "ICE",
    "group": "ICE Core",
    "year": 3,
    "semester": 1
  },
  {
    "code": "ICE314",
    "title": "Digital Communications",
    "credits": "4 (3+1)",
    "prereq": "None",
    "category": "C. ICE Core",
    "dept": "ICE",
    "group": "ICE Core",
    "year": 3,
    "semester": 1
  },
  {
    "code": "ICE322",
    "title": "Digital Signal Processing",
    "credits": "4 (3+1)",
    "prereq": "None",
    "category": "C. ICE Core",
    "dept": "ICE",
    "group": "ICE Core",
    "year": 3,
    "semester": 1
  },
  {
    "code": "ICE370",
    "title": "Applied Numerical Methods",
    "credits": "3",
    "prereq": "None",
    "category": "C. ICE Core",
    "dept": "ICE",
    "group": "ICE Core",
    "year": 3,
    "semester": 1
  },
  {
    "code": "ICE439",
    "title": "Engineering Ethics",
    "credits": "3",
    "prereq": "None",
    "category": "C. ICE Core",
    "dept": "ICE",
    "group": "ICE Core",
    "year": 4,
    "semester": 1
  },
  {
    "code": "ICE441",
    "title": "Wireless & Mobile Communications",
    "credits": "3",
    "prereq": "None",
    "category": "C. ICE Core",
    "dept": "ICE",
    "group": "ICE Core",
    "year": 4,
    "semester": 1
  },
  {
    "code": "ICE473",
    "title": "Project Management, Entrepreneurship and Industry Interaction",
    "credits": "3",
    "prereq": "None",
    "category": "C. ICE Core",
    "dept": "ICE",
    "group": "ICE Core",
    "year": 4,
    "semester": 1
  },
  {
    "code": "ICE496",
    "title": "Capstone Project",
    "credits": "6",
    "prereq": "None",
    "category": "C. ICE Core",
    "dept": "ICE",
    "group": "ICE Core",
    "year": 4,
    "semester": 1
  },
  {
    "code": "ICE453",
    "title": "Computer and Cyber Security",
    "credits": "3",
    "prereq": "None",
    "category": "D. Technical Electives",
    "dept": "ICE",
    "group": "Group A (Information Technology)",
    "year": 4,
    "semester": 1
  },
  {
    "code": "ICE469",
    "title": "Computer Architecture",
    "credits": "3",
    "prereq": "None",
    "category": "D. Technical Electives",
    "dept": "ICE",
    "group": "Group A (Information Technology)",
    "year": 4,
    "semester": 1
  },
  {
    "code": "ICE471",
    "title": "Network Programming",
    "credits": "3",
    "prereq": "None",
    "category": "D. Technical Electives",
    "dept": "ICE",
    "group": "Group A (Information Technology)",
    "year": 4,
    "semester": 1
  },
  {
    "code": "ICE472",
    "title": "Speech & Image Processing",
    "credits": "3",
    "prereq": "None",
    "category": "D. Technical Electives",
    "dept": "ICE",
    "group": "Group A (Information Technology)",
    "year": 4,
    "semester": 1
  },
  {
    "code": "ICE474",
    "title": "Computer Graphics & Visualizations",
    "credits": "3",
    "prereq": "None",
    "category": "D. Technical Electives",
    "dept": "ICE",
    "group": "Group A (Information Technology)",
    "year": 4,
    "semester": 1
  },
  {
    "code": "ICE476",
    "title": "Artificial Intelligence",
    "credits": "3",
    "prereq": "None",
    "category": "D. Technical Electives",
    "dept": "ICE",
    "group": "Group A (Information Technology)",
    "year": 4,
    "semester": 1
  },
  {
    "code": "ICE478",
    "title": "Machine Learning",
    "credits": "3",
    "prereq": "None",
    "category": "D. Technical Electives",
    "dept": "ICE",
    "group": "Group A (Information Technology)",
    "year": 4,
    "semester": 1
  },
  {
    "code": "ICE479",
    "title": "Robotic Engineering",
    "credits": "3",
    "prereq": "None",
    "category": "D. Technical Electives",
    "dept": "ICE",
    "group": "Group A (Information Technology)",
    "year": 4,
    "semester": 1
  },
  {
    "code": "ICE483",
    "title": "Data Science",
    "credits": "3",
    "prereq": "None",
    "category": "D. Technical Electives",
    "dept": "ICE",
    "group": "Group A (Information Technology)",
    "year": 4,
    "semester": 1
  },
  {
    "code": "ICE484",
    "title": "Cyber Ethics and Legal Framework",
    "credits": "3",
    "prereq": "None",
    "category": "D. Technical Electives",
    "dept": "ICE",
    "group": "Group A (Information Technology)",
    "year": 4,
    "semester": 1
  },
  {
    "code": "ICE485",
    "title": "Internet of Things",
    "credits": "3",
    "prereq": "None",
    "category": "D. Technical Electives",
    "dept": "ICE",
    "group": "Group A (Information Technology)",
    "year": 4,
    "semester": 1
  },
  {
    "code": "ICE401",
    "title": "VLSI Circuit Design",
    "credits": "3",
    "prereq": "None",
    "category": "D. Technical Electives",
    "dept": "ICE",
    "group": "Group B (Communication)",
    "year": 4,
    "semester": 1
  },
  {
    "code": "ICE434",
    "title": "Microwave Engineering",
    "credits": "3",
    "prereq": "None",
    "category": "D. Technical Electives",
    "dept": "ICE",
    "group": "Group B (Communication)",
    "year": 4,
    "semester": 1
  },
  {
    "code": "ICE442",
    "title": "Optical Fiber Communications",
    "credits": "3",
    "prereq": "None",
    "category": "D. Technical Electives",
    "dept": "ICE",
    "group": "Group B (Communication)",
    "year": 4,
    "semester": 1
  },
  {
    "code": "ICE446",
    "title": "Satellite Communications",
    "credits": "3",
    "prereq": "None",
    "category": "D. Technical Electives",
    "dept": "ICE",
    "group": "Group B (Communication)",
    "year": 4,
    "semester": 1
  },
  {
    "code": "ICE448",
    "title": "Information Theory and Coding",
    "credits": "3",
    "prereq": "None",
    "category": "D. Technical Electives",
    "dept": "ICE",
    "group": "Group B (Communication)",
    "year": 4,
    "semester": 1
  },
  {
    "code": "ICE452",
    "title": "Multimedia Communications",
    "credits": "3",
    "prereq": "None",
    "category": "D. Technical Electives",
    "dept": "ICE",
    "group": "Group B (Communication)",
    "year": 4,
    "semester": 1
  }
]
};
